### PR TITLE
Paginate list_container_instances call

### PR DESCRIPTION
**Pull request by seiffert**
When running ECS clusters with >100 instances you need to paginate over the result of a `ListContainerInstances` call. If you don't do this, container instances won't be found and cannot be set to draining state before being terminated.

We learned this the hard way and experienced minor outages during cluster updates. 😉 
Please include this change in the example so that others don't have to experience these outages as well.

Review with [`?w=1`](https://github.com/awslabs/ecs-cid-sample/pull/7/files?w=1)

### CODE REVIEW

**Comment by seiffert** [comment]
Hey guys, I don't want to bother you, but this is really a trap for people taking this code as a basis for their implementations! Would you mind taking a look at my change? 

ping @mperi  @cbbarclay @hyandell (found you in [the list of contributors](https://github.com/awslabs/ecs-cid-sample/graphs/contributors))

**Comment by mperi** [comment]
Will submit a fix to this soon.

**Comment by seiffert** [comment]
@mperi this PR contains a fix 😉

**Comment by mperi** [comment]
Pending permissions to merge..should be available in a couple of days.

**Comment by worksewell** [comment]
This change broke the code, the `clusterListResp` variable is referenced but not defined.

**Pull request merged**
